#每6小时调用一次（周六日不启动）
name: Auto Api Pro

on: 
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: '12 */1 * * *'
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and nacl #安装requests模块
      run: |
        pip install requests
    - name: run api #api调用
      env: 
        #github的账号信息
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        #以下是微软的账号信息(修改以下，复制增加账号)
        APP_NUM: ${{ secrets.APP_NUM }} 
        #账号/应用1
        MS_TOKEN: ${{ secrets.MS_TOKEN }} 
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        python runapi.py
